# Generated by Django 6.1.1 on 2026-09-04 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('EDUCATION', 'Education'), ('TECHNOLOGY', 'Technology'), ('ENVIRONMENT', 'Environment'), ('TRANSPORTATION', 'Transportation'), ('HEALTHCARE', 'Healthcare'), ('COMMUNITY', 'Community'), ('BUSINESS', 'Business'), ('AGRICULTURE', 'Agriculture'), ('CAMPUS', 'Campus'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=30)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('SOLVED', 'Solved'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='MEDIUM', max_length=20)),
                ('views', models.PositiveIntegerField(default=0)),
                ('solution_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='problems_pr_status_219cb1_idx'), models.Index(fields=['category', 'created_at'], name='problems_pr_categor_f248bb_idx'), models.Index(fields=['priority', 'created_at'], name='problems_pr_priorit_61b1d5_idx')],
            },
        ),
    ]
