# Generated by Django 6.0.1 on 2026-09-06 04:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembership',
            name='role',
            field=models.CharField(choices=[('PROJECT_MANAGER', 'Project Manager'), ('DEVELOPER', 'Developer'), ('DESIGNER', 'Designer'), ('RESEARCHER', 'Researcher'), ('TESTER', 'Tester'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['project', 'role'], name='teams_teamm_project_7d476e_idx'),
        ),
    ]
