# Generated by Django 6.0.1 on 2026-09-06 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReputationReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(choices=[('PROBLEM_CREATED', 'Problem Created'), ('SOLUTION_PROPOSED', 'Solution Proposed'), ('UPVOTE_RECEIVED', 'Upvote Received'), ('SOLUTION_SELECTED', 'Solution Selected'), ('TASK_COMPLETED', 'Task Completed'), ('PROJECT_COMPLETED', 'Project Completed')], max_length=30)),
                ('points', models.PositiveIntegerField()),
                ('reference_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reputation_rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'reward_type'], name='reputation__user_id_74f35b_idx'), models.Index(fields=['user', 'created_at'], name='reputation__user_id_5ddd69_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'reward_type', 'reference_id'), name='unique_user_reward_reference')],
            },
        ),
    ]
