# Generated by Django 6.1.1 on 2026-09-04 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('SHORTLISTED', 'Shortlisted'), ('SELECTED', 'Selected'), ('REJECTED', 'Rejected')], db_index=True, default='PROPOSED', max_length=20)),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('downvotes', models.PositiveIntegerField(default=0)),
                ('score', models.IntegerField(db_index=True, default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='problems.problem')),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', '-created_at'],
                'indexes': [models.Index(fields=['problem', '-score'], name='solutions_s_problem_58299d_idx'), models.Index(fields=['problem', 'created_at'], name='solutions_s_problem_01eca9_idx'), models.Index(fields=['status', 'created_at'], name='solutions_s_status_d65b7d_idx')],
            },
        ),
    ]
