# Generated by Django 6.1.1 on 2026-09-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('SOLUTION_PROPOSED', 'Solution Proposed'), ('COMMENT', 'Comment'), ('VOTE', 'Solution Vote'), ('SOLUTION_SELECTED', 'Solution Selected'), ('JOIN_REQUEST', 'Join Request'), ('JOIN_APPROVED', 'Join Approved'), ('TASK_ASSIGNED', 'Task Assigned'), ('TASK_STATUS_UPDATED', 'Task Status Updated'), ('PROJECT_COMPLETED', 'Project Completed')], db_index=True, max_length=30),
        ),
    ]
